prometheus:
  appname: prometheus
  image: prom/prometheus:v2.45.3
  replicas: 1
  port: 9090
  storage:
    name: prometheus-storage
    claimName: prometheus-pvc
    mountPath: /prometheus
  
  service:
    name: prometheus-service
    type: NodePort
    port: 9090
    targetPort: 9090
    nodePort: 30007
    selector:
      app: prometheus

  pv:
    name: prometheus-pv
    storage: 5Gi
    accessModes: ReadWriteOnce
    policy: Retain
    hostPath: /skyline/prometheus-data
  
  pvc:
    name: prometheus-pvc
    accessModes: ReadWriteOnce
    storage: 5Gi

  configMap:
    prometheusConfig:
      name: prometheus-config

grafana:
  appname: grafana
  image: grafana/grafana:10.4.14
  replicas: 1
  port: 3000
  storage:
    name: grafana-storage
    claimName: grafana-pvc
    mountPath: /var/lib/grafana
  
  service:
    name: grafana-service
    port: 3000
    targetPort: 3000
    selector:
      app: grafana
  
  pv:
    name: grafana-pv
    storage: 5Gi
    accessModes: ReadWriteOnce
    policy: Retain
    hostPath: /skyline/grafana-data
  
  pvc:
    name: grafana-pvc
    accessModes: ReadWriteOnce
    storage: 5Gi
  
  configMap:
    grafana-dashboard-provider:
      name: grafana-dashboard-provider
    
    grafana-datasources:
      name: grafana-datasources

  ingress:
    enabled: false
    name: grafana-ingress
    ingressClassName: nginx
    host: # YOUR_DNS_or_ROUTE53_DOMAIN_HERE 
    