---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi # 5Gi of storage
  accessModes:
    - ReadWriteOnce # Only one node can read/write at a time
  persistentVolumeReclaimPolicy: Retain  # Do not delete PV if PVC is removed
  hostPath:
    path: /mnt/prometheus-data # Path on the worker node
