apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany # Multiple nodes can read/write at a time
  resources:
    requests:
      storage: 5Gi # 5Gi of storage