apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce # Only one node can read/write at a time
  resources:
    requests:
      storage: 5Gi # 5Gi of storage