---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: {{ .Values.prometheus.service.selector.app }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.targetPort }}
      nodePort: {{ .Values.prometheus.service.nodePort }}