apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.4.14
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-dashboard  # Ensure this matches the volume name below
          mountPath: /var/lib/grafana
    volumes:
    - name: grafana-dashboard  # This should match the volumeMount name
      configMap:
        name: gateway-dashboard-kz-json


---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
