apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce # Only one node can read/write at a time
  resources:
    requests:
      storage: 5Gi 

