apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi # 5Gi of storage
  accessModes:
    - ReadWriteMany # Multiple nodes can read/write at a time
  persistentVolumeReclaimPolicy: Retain  # Do not delete PV if PVC is removed
  hostPath:
    path: /mnt/grafana-data # Path on the worker node
