---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.grafana.service.selector.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}
