apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.grafana.pvc.name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.grafana.pvc.accessModes }} # Only one node can read/write at a time
  resources:
    requests:
      storage: {{ .Values.grafana.pvc.storage }} 

