apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.grafana.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.grafana.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.grafana.service.name }}
            port: 
              number: {{ .Values.grafana.service.port }}